/*
 * Copyright (c) 2019, Tulsiram Rathod.
 */

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "com.tulsiram.crypto.sample"
    compileSdkVersion 37

    defaultConfig {
        applicationId "com.tulsiram.crypto.sample"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.runner
    androidTestImplementation libs.androidx.espresso.core
    implementation project(path: ':crypto')
}
